# 1. 공식 Airflow 이미지를 기반으로 시작
FROM apache/airflow:3.1.1
# FROM apache/airflow:2.10.3

# 2. (선택사항) lxml, mysql-connector-python 등이 시스템 라이브러리를 필요로 할 수 있음
# USER root
# RUN apt-get update && apt-get install -y libxml2-dev libxslt-dev default-libmysqlclient-dev && apt-get clean
# USER airflow

# 3. 방금 만든 requirements.txt 파일을 컨테이너 안으로 복사
COPY requirements.txt .

# 4. pip install 실행 (이 작업은 '빌드' 시 딱 한 번만 실행됨)
RUN pip install --no-cache-dir -r requirements.txt